networks:
  chatnet:
    driver: bridge
services:
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres1:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
    
      # Postgres
      DB_HOST: postgres1 
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}_1

    networks:
      - chatnet
    restart: unless-stopped

  postgres1:
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}_1
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chatnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}_1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
 
  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres2:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
    
      # Postgres
      DB_HOST: postgres2 
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}_2

    networks:
      - chatnet
    restart: unless-stopped

  postgres2:
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}_2
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - chatnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}_2"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    
  backend3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres3:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
    
      # Postgres
      DB_HOST: postgres3
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}_3

    networks:
      - chatnet
    restart: unless-stopped

  postgres3:
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}_3
    volumes:
      - postgres_data3:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - chatnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}_3"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    
volumes:
  postgres_data1:
  postgres_data2:
  postgres_data3:
